# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='domain.proto',
  package='gbf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64omain.proto\x12\x03gbf\"\xa8\x01\n\x08RaidBoss\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x05image\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08lastSeen\x18\x03 \x01(\x03\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x1f\n\x08language\x18\x05 \x01(\x0e\x32\r.gbf.Language\x12\x1b\n\x0etranslatedName\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_imageB\x11\n\x0f_translatedName*6\n\x08Language\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08JAPANESE\x10\x01\x12\x0b\n\x07\x45NGLISH\x10\x02\x62\x06proto3'
)

_LANGUAGE = _descriptor.EnumDescriptor(
  name='Language',
  full_name='gbf.Language',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JAPANESE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENGLISH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=192,
  serialized_end=246,
)
_sym_db.RegisterEnumDescriptor(_LANGUAGE)

Language = enum_type_wrapper.EnumTypeWrapper(_LANGUAGE)
UNSPECIFIED = 0
JAPANESE = 1
ENGLISH = 2



_RAIDBOSS = _descriptor.Descriptor(
  name='RaidBoss',
  full_name='gbf.RaidBoss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gbf.RaidBoss.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='gbf.RaidBoss.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastSeen', full_name='gbf.RaidBoss.lastSeen', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='gbf.RaidBoss.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='gbf.RaidBoss.language', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translatedName', full_name='gbf.RaidBoss.translatedName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_image', full_name='gbf.RaidBoss._image',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_translatedName', full_name='gbf.RaidBoss._translatedName',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=22,
  serialized_end=190,
)

_RAIDBOSS.fields_by_name['language'].enum_type = _LANGUAGE
_RAIDBOSS.oneofs_by_name['_image'].fields.append(
  _RAIDBOSS.fields_by_name['image'])
_RAIDBOSS.fields_by_name['image'].containing_oneof = _RAIDBOSS.oneofs_by_name['_image']
_RAIDBOSS.oneofs_by_name['_translatedName'].fields.append(
  _RAIDBOSS.fields_by_name['translatedName'])
_RAIDBOSS.fields_by_name['translatedName'].containing_oneof = _RAIDBOSS.oneofs_by_name['_translatedName']
DESCRIPTOR.message_types_by_name['RaidBoss'] = _RAIDBOSS
DESCRIPTOR.enum_types_by_name['Language'] = _LANGUAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaidBoss = _reflection.GeneratedProtocolMessageType('RaidBoss', (_message.Message,), {
  'DESCRIPTOR' : _RAIDBOSS,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:gbf.RaidBoss)
  })
_sym_db.RegisterMessage(RaidBoss)


# @@protoc_insertion_point(module_scope)
