# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raidtweet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import domain_pb2 as domain__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raidtweet.proto',
  package='gbf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fraidtweet.proto\x12\x03gbf\x1a\x0c\x64omain.proto\"\xb2\x01\n\x11RaidTweetResponse\x12\x10\n\x08\x62ossName\x18\x01 \x01(\t\x12\x0e\n\x06raidId\x18\x02 \x01(\t\x12\x12\n\nscreenName\x18\x03 \x01(\t\x12\x0f\n\x07tweetId\x18\x04 \x01(\x03\x12\x14\n\x0cprofileImage\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x11\n\tcreatedAt\x18\x07 \x01(\x03\x12\x1f\n\x08language\x18\x08 \x01(\x0e\x32\r.gbf.Languageb\x06proto3'
  ,
  dependencies=[domain__pb2.DESCRIPTOR,])




_RAIDTWEETRESPONSE = _descriptor.Descriptor(
  name='RaidTweetResponse',
  full_name='gbf.RaidTweetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bossName', full_name='gbf.RaidTweetResponse.bossName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raidId', full_name='gbf.RaidTweetResponse.raidId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screenName', full_name='gbf.RaidTweetResponse.screenName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tweetId', full_name='gbf.RaidTweetResponse.tweetId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profileImage', full_name='gbf.RaidTweetResponse.profileImage', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='gbf.RaidTweetResponse.text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createdAt', full_name='gbf.RaidTweetResponse.createdAt', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='gbf.RaidTweetResponse.language', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=217,
)

_RAIDTWEETRESPONSE.fields_by_name['language'].enum_type = domain__pb2._LANGUAGE
DESCRIPTOR.message_types_by_name['RaidTweetResponse'] = _RAIDTWEETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaidTweetResponse = _reflection.GeneratedProtocolMessageType('RaidTweetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RAIDTWEETRESPONSE,
  '__module__' : 'raidtweet_pb2'
  # @@protoc_insertion_point(class_scope:gbf.RaidTweetResponse)
  })
_sym_db.RegisterMessage(RaidTweetResponse)


# @@protoc_insertion_point(module_scope)
