# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raidboss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import domain_pb2 as domain__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raidboss.proto',
  package='gbf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eraidboss.proto\x12\x03gbf\x1a\x0c\x64omain.proto\"7\n\x12RaidBossesResponse\x12!\n\nraidBosses\x18\x01 \x03(\x0b\x32\r.gbf.RaidBossb\x06proto3'
  ,
  dependencies=[domain__pb2.DESCRIPTOR,])




_RAIDBOSSESRESPONSE = _descriptor.Descriptor(
  name='RaidBossesResponse',
  full_name='gbf.RaidBossesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raidBosses', full_name='gbf.RaidBossesResponse.raidBosses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=92,
)

_RAIDBOSSESRESPONSE.fields_by_name['raidBosses'].message_type = domain__pb2._RAIDBOSS
DESCRIPTOR.message_types_by_name['RaidBossesResponse'] = _RAIDBOSSESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaidBossesResponse = _reflection.GeneratedProtocolMessageType('RaidBossesResponse', (_message.Message,), {
  'DESCRIPTOR' : _RAIDBOSSESRESPONSE,
  '__module__' : 'raidboss_pb2'
  # @@protoc_insertion_point(class_scope:gbf.RaidBossesResponse)
  })
_sym_db.RegisterMessage(RaidBossesResponse)


# @@protoc_insertion_point(module_scope)
